# app/config/security.yml
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
                    entity:
                        class: AppBundle:User

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12

    firewalls:
        main:
                  anonymous: ~
                  form_login:
                    use_referer: true
                    default_target_path: /home
                    login_path: login
                    check_path: login
                  pattern:    ^/
                  http_basic: ~
                  provider: our_db_provider
                  logout:
                    path: /logout
                    target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~


    access_control:
    # require ROLE_ADMIN for /admin*
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/home, roles: ROLE_USER }
    - { path: ^/category, roles: ROLE_USER }